# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionedarticle',
            name='message_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
