# Generated by Django 3.2.16 on 2023-03-30 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0072_auto_20230330_1147'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commission', '0003_alter_commissionedarticle_commissioning_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionedarticle',
            name='commissioned_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissioned_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commissionedarticle',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article'),
        ),
    ]
