# Generated by Django 3.2.16 on 2023-03-30 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0059_alter_prepublicationchecklistitem_completed_by'),
        ('commission', '0005_commissionedarticle_commissioned_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionedarticle',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journal'),
        ),
    ]
