# Generated by Django 3.2.16 on 2023-03-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0006_commissionedarticle_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionedarticle',
            name='author_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
