# Generated by Django 3.2.16 on 2023-03-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0007_commissionedarticle_author_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.TextField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.section')),
            ],
        ),
    ]
