# Generated by Django 3.2.16 on 2023-03-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0008_commissiontemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontemplate',
            name='name',
            field=models.CharField(default='Template', max_length=255),
            preserve_default=False,
        ),
    ]
