# Generated by Django 3.2.16 on 2023-03-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0009_commissiontemplate_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commissionedarticle',
            old_name='author_accepted',
            new_name='author_decision_date',
        ),
        migrations.AddField(
            model_name='commissionedarticle',
            name='author_decision',
            field=models.CharField(blank=True, choices=[('accept', 'Accepted'), ('declined', 'Declined')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='commissionedarticle',
            name='author_decision_editor_check',
            field=models.BooleanField(default=False),
        ),
    ]
