# Generated by Django 3.2.16 on 2023-03-30 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0072_auto_20230330_1147'),
        ('commission', '0010_auto_20230330_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontemplate',
            name='subject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionedarticle',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='submission.article'),
        ),
    ]
