# Generated by Django 3.2.16 on 2023-04-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0011_auto_20230330_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commissionedarticle',
            name='commissioned_section',
        ),
        migrations.AddField(
            model_name='commissionedarticle',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
