# Generated by Django 3.2.16 on 2023-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0015_auto_20230419_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionedarticle',
            name='submission_reminder_after_sent',
            field=models.DateTimeField(blank=True, help_text='The date and time the after submission deadline reminder is sent.', null=True),
        ),
        migrations.AddField(
            model_name='commissionedarticle',
            name='submission_reminder_before_sent',
            field=models.DateTimeField(blank=True, help_text='The date and time the before submission deadline reminder is sent.', null=True),
        ),
    ]
