# Generated by Django 3.2.16 on 2023-05-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0016_auto_20230420_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissiontemplate',
            name='sent_on_acceptance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='commissiontemplate',
            name='name',
            field=models.CharField(help_text='The name of your template', max_length=255),
        ),
        migrations.AlterField(
            model_name='commissiontemplate',
            name='section',
            field=models.ForeignKey(help_text='The section your template is to be used for', on_delete=django.db.models.deletion.CASCADE, to='submission.section'),
        ),
    ]
