# Generated by Django 3.2.16 on 2023-05-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0017_auto_20230512_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commissionedarticle',
            name='deadline',
            field=models.DateField(blank=True, help_text='The deadline by which the author must accept or decline the commission request.', null=True, verbose_name='Request deadline'),
        ),
    ]
